lib/ship_web/router.ex
defmodule ShipWeb.Router do
  use ShipWeb, :router

  import ShipWeb.PlayerAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShipWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_player
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShipWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShipWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ShipWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", ShipWeb do
    pipe_through [:browser, :redirect_if_player_is_authenticated]

    get "/players/register", PlayerRegistrationController, :new
    post "/players/register", PlayerRegistrationController, :create
    get "/players/log_in", PlayerSessionController, :new
    post "/players/log_in", PlayerSessionController, :create
    get "/players/reset_password", PlayerResetPasswordController, :new
    post "/players/reset_password", PlayerResetPasswordController, :create
    get "/players/reset_password/:token", PlayerResetPasswordController, :edit
    put "/players/reset_password/:token", PlayerResetPasswordController, :update
  end

  scope "/", ShipWeb do
    pipe_through [:browser, :require_authenticated_player]


    # live_session :require_authenticated_player,
    # on_mount: [{ShipWeb.PlayerAuth, :ensure_authenticated}] do
    live "/game", GameLive

    # end

    get "/players/settings", PlayerSettingsController, :edit
    put "/players/settings", PlayerSettingsController, :update
    get "/players/settings/confirm_email/:token", PlayerSettingsController, :confirm_email


  end

  scope "/", ShipWeb do
    pipe_through [:browser]

    delete "/players/log_out", PlayerSessionController, :delete
    get "/players/confirm", PlayerConfirmationController, :new
    post "/players/confirm", PlayerConfirmationController, :create
    get "/players/confirm/:token", PlayerConfirmationController, :edit
    post "/players/confirm/:token", PlayerConfirmationController, :update
  end
end

lib/ship_web/views/layout_view.ex
defmodule ShipWeb.LayoutView do
  use ShipWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/ship_web/templates/layout/_player_menu.html.heex
<ul>
<%= if @current_player do %>
  <li><%= @current_player.email %></li>
  <li><%= link "Settings", to: Routes.player_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.player_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.player_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.player_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/ship_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/ship_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/ship_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Ship", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
<!--    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_player_menu.html", assigns %>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header> -->
    <%= @inner_content %>
  </body>
</html>